# Generated by Django 4.1.7 on 2023-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id_primary', models.CharField(max_length=33, primary_key=True, serialize=False)),
                ('name_station', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('empty_slot', models.IntegerField()),
                ('altitude', models.IntegerField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.IntegerField()),
                ('normal_bikes', models.IntegerField()),
                ('payment_key', models.BooleanField()),
                ('payment_transitcard', models.BooleanField()),
                ('payment_creditcard', models.BooleanField()),
                ('payment_phone', models.BooleanField()),
                ('renting', models.IntegerField()),
                ('returning_val', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.CharField(max_length=10)),
                ('free_bikes', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
