# Generated by Django 4.1.7 on 2023-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
