# Generated by Django 4.1.7 on 2023-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0002_alter_stations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='id_primary',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stations',
            name='name_station',
            field=models.CharField(max_length=55),
        ),
    ]
